<?php

namespace App\Services\user;

use App\Services\BaseServices;

class RegisterUser extends BaseServices
{
    public function rules(): array
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function execute(array $data)
    {

    }
}
